In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./dados_worldbank.csv')

In [3]:
df

,dataset_id,dataset_unique_id,status,nome_dataset,fonte_dataset,ultimo_update_dataset,link,link_antigo,data_criado,periodicidade,versoes,resource_id,resource_unique_id,nome_fonte,url_fonte,web_url_fonte,formato_fonte,publicacao_fonte,visibilidade,tamanho_fonte
0,f460bdea-2df5-ef11-be21-6045bd05bd87,66762,PUBLISHED,Philippines - Household Survey for Indigenous ...,MICRODATA,2025-02-11T00:00:00+00:00,NaN,NaN,NaN,NaN,1,f3bcc0f1-2df5-ef11-be21-6045bd05bd87,DR0094956,Visit the Microdata Library to access data and...,NaN,https://microdata.worldbank.org/index.php/cata...,HTML,NaN,Public,NaN
1,90535620-d1f3-ef11-be20-6045bd08838c,66751,PUBLISHED,Tunisia - World Bank Group Country Survey 2024,MICRODATA,2025-02-24T00:00:00+00:00,NaN,NaN,NaN,NaN,1,9d138826-d1f3-ef11-be20-000d3a3acf37,DR0094947,Visit the Microdata Library to access data and...,NaN,https://microdata.worldbank.org/index.php/cata...,HTML,NaN,Public,NaN
2,de5c52be-cff3-ef11-be20-000d3a3acf37,66750,PUBLISHED,Togo - World Bank Group Country Survey 2024,MICRODATA,2025-02-24T00:00:00+00:00,NaN,NaN,NaN,NaN,1,3ddb03cb-cff3-ef11-be21-000d3a5a9a5f,DR0094946,Visit the Microdata Library to access data and...,NaN,https://microdata.worldbank.org/index.php/cata...,HTML,NaN,Public,NaN
3,7b6756f1-c2f3-ef11-be20-000d3a36643e,66749,PUBLISHED,South Sudan - World Bank Group Country Survey ...,MICRODATA,2025-02-24T00:00:00+00:00,NaN,NaN,NaN,NaN,1,dd466bf7-c2f3-ef11-be20-000d3a36643e,DR0094945,Visit the Microdata Library to access data and...,NaN,https://microdata.worldbank.org/index.php/cata...,HTML,NaN,Public,NaN
4,16a4b2df-bcf3-ef11-be20-000d3a36643e,66748,PUBLISHED,Solomon Islands - World Bank Group Country Sur...,MICRODATA,2025-02-24T00:00:00+00:00,NaN,NaN,NaN,NaN,1,1071bfe9-bcf3-ef11-be21-000d3a5a9a5f,DR0094944,Visit the Microdata Library to access data and...,NaN,https://microdata.worldbank.org/index.php/cata...,HTML,NaN,Public,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10718,62be4e01-3475-eb11-a812-000d3a593ef9,22891,PUBLISHED,South Africa - Bureau of Market Research Surve...,MICRODATA,2013-01-10T00:00:00+00:00,NaN,https://datacatalog.worldbank.org/dataset/sout...,NaN,NaN,7,acbe4e01-3475-eb11-a812-000d3a593ef9,DR0026170,Visit the Microdata Library to access data and...,NaN,https://microdata.worldbank.org/index.php/cata...,NaN,NaN,Public,NaN
10719,ebf14cfb-3375-eb11-a812-000d3a593ef9,22890,PUBLISHED,"Egypt, Arab Rep. - Population Housing and Esta...",MICRODATA,2012-05-03T00:00:00+00:00,NaN,https://datacatalog.worldbank.org/dataset/egyp...,NaN,NaN,6,fcb6e600-3475-eb11-a812-000d3a59395d,DR0026169,Visit the Microdata Library to access data and...,NaN,https://microdata.worldbank.org/index.php/cata...,NaN,NaN,Public,NaN
10720,664c52f5-3375-eb11-a812-000d3a593ef9,22889,PUBLISHED,South Africa - Bureau of Market Research Surve...,MICRODATA,2013-01-10T00:00:00+00:00,NaN,https://datacatalog.worldbank.org/dataset/sout...,NaN,NaN,6,064de7fa-3375-eb11-a812-000d3a59395d,DR0026168,Visit the Microdata Library to access data and...,NaN,https://microdata.worldbank.org/index.php/cata...,NaN,NaN,Public,NaN
10721,fac3822f-1c75-eb11-a812-000d3a59395d,22021,PUBLISHED,Guinea - Impact Evaluation of Performance-base...,MICRODATA,2014-09-17T00:00:00+00:00,NaN,https://datacatalog.worldbank.org/dataset/guin...,NaN,NaN,10,01ec8730-1c75-eb11-a812-000d3a593ef9,DR0025239,Visit the Microdata Library to access data and...,NaN,https://microdata.worldbank.org/index.php/cata...,NaN,NaN,Public,NaN
10722,23a3f279-1675-eb11-a812-000d3a593ef9,21782,PUBLISHED,Liberia - National Household Forest Survey 201...,MICRODATA,2020-09-23T00:00:00+00:00,NaN,https://datacatalog.worldbank.org/dataset/libe...,NaN,NaN,7,8a516680-1675-eb11-a812-000d3a59395d,DR0024813,Visit the Microdata Library to access data and...,NaN,https://microdata.worldbank.org/index.php/cata...,NaN,NaN,Public,NaN

In [ ]:
# selecionar apenas dados com periodicidade e com formatos de recuros validos
df = df[(df.formato_fonte.str.contains(r'csv|cvs|xls|zip|json|xml|rar|api|excel|html', case=False, na=True)) & (df.periodicidade.notna())]

In [6]:
df

,dataset_id,dataset_unique_id,status,nome_dataset,fonte_dataset,ultimo_update_dataset,link,link_antigo,data_criado,periodicidade,versoes,resource_id,resource_unique_id,nome_fonte,url_fonte,web_url_fonte,formato_fonte,publicacao_fonte,visibilidade,tamanho_fonte
40,6e0be9e2-f0e2-ef11-a731-000d3a5c4d2d,66692,PUBLISHED,MIGA Paid in Capital & Voting Power of Member ...,FINANCE,2024-10-21T00:00:00+00:00,NaN,NaN,NaN,Annual,1,4c63ecec-f0e2-ef11-a731-000d3a597c4c,DR0094885,Visit World Bank Group Finances One,https://financesone.worldbank.org/d/DS01777,https://financesone.worldbank.org/d/DS01777,NaN,NaN,Public,NaN
54,779dc546-21dc-ef11-a731-000d3a597c4c,66672,PUBLISHED,Elasticities of Substitution for 28 Countries,Others,NaN,NaN,NaN,NaN,Annual,1,7ca1fd25-25dc-ef11-a731-000d3a597c4c,DR0094866,Elasticities of substitution,https://datacatalogfiles.worldbank.org/ddh-pub...,NaN,ZIP,NaN,Public,NaN
237,a5adfd1e-c86e-ef11-a671-0022480c0cc1,66231,PUBLISHED,IBRD Key Ratios and Performance Metrics,FINANCE,2014-12-16T00:00:00+00:00,NaN,NaN,NaN,Quarter,1,dae8ed25-c86e-ef11-a671-0022480c0cc1,DR0094366,Visit World Bank Group Finances One,https://financesone.worldbank.org/d/DS01552,https://financesone.worldbank.org/d/DS01552,NaN,NaN,Public,NaN
238,0374f8f6-c76e-ef11-a670-6045bd05054b,66230,PUBLISHED,MIGA Condensed Balance Sheets,FINANCE,2014-10-09T00:00:00+00:00,NaN,NaN,NaN,Quarter,1,62ad97fd-c76e-ef11-a670-6045bd05054b,DR0094365,Visit World Bank Group Finances One,https://financesone.worldbank.org/d/DS01547,https://financesone.worldbank.org/d/DS01547,NaN,NaN,Public,NaN
239,e8dd9cd1-c76e-ef11-a671-000d3a36f824,66229,PUBLISHED,IFC Condensed Balance Sheets,FINANCE,2014-10-09T00:00:00+00:00,NaN,NaN,NaN,Quarter,1,b0d2c4d7-c76e-ef11-a671-000d3a36f824,DR0094364,Visit World Bank Group Finances One,https://financesone.worldbank.org/d/DS01546,https://financesone.worldbank.org/d/DS01546,NaN,NaN,Public,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10686,13d39f39-b3c7-eb11-bacc-000d3a5a1a58,37533,PUBLISHED,IBRD Summary of Allocable Income,FINANCE,2014-12-16T00:00:00+00:00,NaN,https://datacatalog.worldbank.org/dataset/ibrd...,NaN,Quarter,7,f466c53f-b3c7-eb11-bacc-000d3a5a1a58,DR0045355,Visit World Bank Group Finances One,https://financesone.worldbank.org/d/DS00995,https://financesone.worldbank.org/d/DS00995,NaN,NaN,Public,NaN
10687,9fea7928-b3c7-eb11-bacc-000d3a5a1c19,37531,PUBLISHED,IFC Summary Consolidated Income Statement,FINANCE,2014-12-16T00:00:00+00:00,NaN,https://datacatalog.worldbank.org/dataset/ifc-...,NaN,Quarter,7,435e842d-b3c7-eb11-bacc-000d3a5a1a58,DR0045353,Visit World Bank Group Finances One,https://financesone.worldbank.org/d/DS00989,https://financesone.worldbank.org/d/DS00989,NaN,NaN,Public,NaN
10688,8202921b-b3c7-eb11-bacc-000d3a5a1a58,37530,PUBLISHED,IFC Summary Consolidated Statement of Comprehe...,FINANCE,2014-12-16T00:00:00+00:00,NaN,https://datacatalog.worldbank.org/dataset/ifc-...,NaN,Quarter,7,85b67522-b3c7-eb11-bacc-000d3a5a1c19,DR0045352,Visit World Bank Group Finances One,https://financesone.worldbank.org/d/DS00997,https://financesone.worldbank.org/d/DS00997,NaN,NaN,Public,NaN
10697,f493bf49-93c7-eb11-bacc-000d3a5a1c19,37525,PUBLISHED,IBRD and IDA Net Flows & Commitments,FINANCE,2020-11-18T00:00:00+00:00,NaN,https://datacatalog.worldbank.org/dataset/ibrd...,NaN,Month,8,54c3254b-93c7-eb11-bacc-000d3a5a1a58,DR0045332,Visit World Bank Group Finances One,https://financesone.worldbank.org/d/DS00044,https://financesone.worldbank.org/d/DS00044,NaN,NaN,Public,NaN
10698,2f15fd3c-93c7-eb11-bacc-000d3a5a1c19,37524,PUBLISHED,World Bank (IBRD) Bonds (1947-Present),FINANCE,2019-03-07T00:00:00+00:00,NaN,https://datacatalog.worldbank.org/dataset/worl...,NaN,Day,9,8a88c243-93c7-eb11-bacc-000d3a5a1c19,DR0045331,Visit World Bank Group Finances One,https://financesone.worldbank.org/d/DS00052,https://financesone.worldbank.org/d/DS00052,NaN,NaN,Public,NaN

In [ ]:
# remover linhas duplicadas
df = df[['dataset_id', 'dataset_unique_id', 'nome_dataset', 'link', 'link_antigo']].drop_duplicates()

In [8]:
df.to_csv('./candidatos_schema_matching_worldbank.csv', index=False)