In [1]:
import pandas as pd
from fuzzywuzzy import fuzz
import numpy as np

In [2]:
df = pd.read_csv('./datasets_datagov_eua.csv',sep='|')

C:\Users\user\AppData\Local\Temp\ipykernel_13572\4073272607.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./datasets_datagov_eua.csv',sep='|')

In [3]:
df

,dataset_id,qtd_arquivos,privado,tipo,nome,titulo,descricao,url,nivel_acesso,formato_arquivo,id_arquivo,url_arquivo
0,f9880479-bf5c-477c-ba8e-0651a0e054a5,4,False,dataset,lottery-powerball-winning-numbers-beginning-2010,Lottery Powerball Winning Numbers: Beginning 2010,Go to http://on.ny.gov/1GpWiHD on the New York...,https://catalog.data.gov/dataset/lottery-power...,public,CSV,a70c071c-4712-4d6f-98a3-48d8b33ee632,https://data.ny.gov/api/views/d6yy-54nr/rows.c...
1,f9880479-bf5c-477c-ba8e-0651a0e054a5,4,False,dataset,lottery-powerball-winning-numbers-beginning-2010,Lottery Powerball Winning Numbers: Beginning 2010,Go to http://on.ny.gov/1GpWiHD on the New York...,https://catalog.data.gov/dataset/lottery-power...,public,RDF,889b78f1-9837-4d7a-a31b-fbfccb0a6d44,https://data.ny.gov/api/views/d6yy-54nr/rows.r...
2,f9880479-bf5c-477c-ba8e-0651a0e054a5,4,False,dataset,lottery-powerball-winning-numbers-beginning-2010,Lottery Powerball Winning Numbers: Beginning 2010,Go to http://on.ny.gov/1GpWiHD on the New York...,https://catalog.data.gov/dataset/lottery-power...,public,JSON,074f73f1-5722-46a5-8646-c0c6822d6602,https://data.ny.gov/api/views/d6yy-54nr/rows.j...
3,f9880479-bf5c-477c-ba8e-0651a0e054a5,4,False,dataset,lottery-powerball-winning-numbers-beginning-2010,Lottery Powerball Winning Numbers: Beginning 2010,Go to http://on.ny.gov/1GpWiHD on the New York...,https://catalog.data.gov/dataset/lottery-power...,public,XML,525f0494-e3b2-47b7-85da-9755b185b265,https://data.ny.gov/api/views/d6yy-54nr/rows.x...
4,844dbad1-ee1e-44b8-9799-34cb7ed24640,4,False,dataset,electric-vehicle-population-data,Electric Vehicle Population Data,This dataset shows the Battery Electric Vehicl...,https://catalog.data.gov/dataset/electric-vehi...,public,CSV,fa51be35-691f-45d2-9f3e-535877965e69,https://data.wa.gov/api/views/f6w7-q2d2/rows.c...
...,...,...,...,...,...,...,...,...,...,...,...,...
1977591,90cc4180-efe4-4268-a6c5-12e1a304c699,7,False,dataset,digital-geomorphic-gis-map-of-the-ocracoke-are...,Digital Geomorphic-GIS Map of the Ocracoke Are...,The Digital Geomorphic-GIS Map of the Ocracoke...,https://catalog.data.gov/dataset/digital-geomo...,public,PDF,15dda178-51c9-498d-8dd9-f2ff9ca7d3f3,https://irma.nps.gov/DataStore/DownloadFile/65...
1977592,90cc4180-efe4-4268-a6c5-12e1a304c699,7,False,dataset,digital-geomorphic-gis-map-of-the-ocracoke-are...,Digital Geomorphic-GIS Map of the Ocracoke Are...,The Digital Geomorphic-GIS Map of the Ocracoke...,https://catalog.data.gov/dataset/digital-geomo...,public,ZIP,f8bd8b64-361e-43a8-8c1c-b506e2fd9204,https://irma.nps.gov/DataStore/DownloadFile/65...
1977593,90cc4180-efe4-4268-a6c5-12e1a304c699,7,False,dataset,digital-geomorphic-gis-map-of-the-ocracoke-are...,Digital Geomorphic-GIS Map of the Ocracoke Are...,The Digital Geomorphic-GIS Map of the Ocracoke...,https://catalog.data.gov/dataset/digital-geomo...,public,ZIP,bd13c673-afa7-4cb4-8f82-facecc2a7dc1,https://irma.nps.gov/DataStore/DownloadFile/65...
1977594,90cc4180-efe4-4268-a6c5-12e1a304c699,7,False,dataset,digital-geomorphic-gis-map-of-the-ocracoke-are...,Digital Geomorphic-GIS Map of the Ocracoke Are...,The Digital Geomorphic-GIS Map of the Ocracoke...,https://catalog.data.gov/dataset/digital-geomo...,public,ZIP,9b96d9f3-2fcc-45a4-8751-097588c5e953,https://irma.nps.gov/DataStore/DownloadFile/55...
1977595,90cc4180-efe4-4268-a6c5-12e1a304c699,7,False,dataset,digital-geomorphic-gis-map-of-the-ocracoke-are...,Digital Geomorphic-GIS Map of the Ocracoke Are...,The Digital Geomorphic-GIS Map of the Ocracoke...,https://catalog.data.gov/dataset/digital-geomo...,public,ZIP,462b8ade-5f8c-46c3-8982-111de3edfb97,https://irma.nps.gov/DataStore/DownloadFile/65...

In [4]:
df.formato_arquivo = df.formato_arquivo.str.upper()

In [5]:
df_valido = df[(df.formato_arquivo.str.contains(r'csv|cvs|xls|zip|json|rar|comma|tsv|excel', case=False, na=False))]
df_invalido = df[(df.formato_arquivo.str.contains(r'geo|xml|pdf', case=False, na=False))]
# df = df[(df.formato_arquivo.str.contains(r'csv|cvs|xls|zip|json|xml|rar|comma|tsv|excel', case=False, na=True))]

In [6]:
df_valido = df_valido[(df_valido.qtd_arquivos > 0)]
df_invalido = df_invalido[(df_invalido.qtd_arquivos > 0)]
# df = df[(df.qtd_arquivos > 1) | (df.qtd_arquivos.isna())]

In [7]:
df = df[df.dataset_id.isin(df_valido.dataset_id)]
df = df[~df.dataset_id.isin(df_invalido.dataset_id)]

In [8]:
df = df[(df.nivel_acesso == 'public') | (df.nivel_acesso.isna())]
# df = df[(df.nivel_acesso == 'public') | (df.nivel_acesso.isna())]

In [9]:
df

,dataset_id,qtd_arquivos,privado,tipo,nome,titulo,descricao,url,nivel_acesso,formato_arquivo,id_arquivo,url_arquivo
12,76295ca9-bb8b-42ba-806b-a18b38054ce2,2,False,dataset,supply-chain-greenhouse-gas-emission-factors-v...,Supply Chain Greenhouse Gas Emission Factors v...,The datasets comprise greenhouse gas (GHG) emi...,https://catalog.data.gov/dataset/supply-chain-...,public,CSV,19c7c85f-d3de-4a9b-9559-f8ac44f3a168,https://pasteur.epa.gov/uploads/10.23719/15311...
13,76295ca9-bb8b-42ba-806b-a18b38054ce2,2,False,dataset,supply-chain-greenhouse-gas-emission-factors-v...,Supply Chain Greenhouse Gas Emission Factors v...,The datasets comprise greenhouse gas (GHG) emi...,https://catalog.data.gov/dataset/supply-chain-...,public,CSV,aaf240c3-b948-40e6-9fe8-8f2aff51c53c,https://pasteur.epa.gov/uploads/10.23719/15311...
15,6291b7de-330d-40e9-ad0e-a8aa4082dfe8,2,False,dataset,baby-names-from-social-security-card-applicati...,Baby Names from Social Security Card Applicati...,"The data (name, year of birth, sex, and number...",https://catalog.data.gov/dataset/baby-names-fr...,public,HTML,5bd8407f-3f0c-45ff-9337-bc1235c10e5c,https://www.ssa.gov/oact/babynames/index.html
16,6291b7de-330d-40e9-ad0e-a8aa4082dfe8,2,False,dataset,baby-names-from-social-security-card-applicati...,Baby Names from Social Security Card Applicati...,"The data (name, year of birth, sex, and number...",https://catalog.data.gov/dataset/baby-names-fr...,public,ZIP,746392ff-35f6-446d-9bf5-a611011ee3f8,https://www.ssa.gov/oact/babynames/names.zip
17,07f079ea-4c60-4528-a61b-f5e815ef77cb,1,False,dataset,fruit-and-vegetable-prices,Fruit and Vegetable Prices,How much do fruits and vegetables cost? ERS es...,https://catalog.data.gov/dataset/fruit-and-veg...,public,XLS,e3bb62e0-8c97-4ff0-9c7b-b3d7fb4b06fc,http://www.ers.usda.gov/data-products/fruit-an...
...,...,...,...,...,...,...,...,...,...,...,...,...
1977584,1b177cb6-e8f9-47a5-a401-26d2caf67a1a,1,False,dataset,hydrographic-and-impairment-statistics-databas...,Hydrographic and Impairment Statistics Databas...,Hydrographic and Impairment Statistics (HIS) i...,https://catalog.data.gov/dataset/hydrographic-...,public,ZIP,676c190e-71a5-427e-9a75-232ad81e0790,https://irma.nps.gov/DataStore/DownloadFile/70...
1977585,cf4a7126-b376-4321-9ef6-dc99ff9f0c3d,1,False,dataset,hawaii-volcanoes-national-park-tract-and-bound...,Hawaii Volcanoes National Park Tract and Bound...,These ESRI shape files are of National Park Se...,https://catalog.data.gov/dataset/hawaii-volcan...,public,ZIP,e2650a42-eb71-437a-9623-eae673fa4d24,https://irma.nps.gov/DataStore/DownloadFile/69...
1977586,3c8e2d14-25a0-4021-bcf0-a63341ea91df,1,False,dataset,hydrographic-and-impairment-statistics-databas...,Hydrographic and Impairment Statistics Databas...,Hydrographic and Impairment Statistics (HIS) i...,https://catalog.data.gov/dataset/hydrographic-...,public,ZIP,15d1492b-488e-4f39-aa70-735201ba44e2,https://irma.nps.gov/DataStore/DownloadFile/70...
1977587,feec6337-6fdb-455d-b274-6e86cfddb141,2,False,dataset,rocky-mountain-network-soils-database-rocky-mo...,Rocky Mountain Network Soils Database - Rocky ...,Wetlands Ecological Integrity Backend Database...,https://catalog.data.gov/dataset/rocky-mountai...,public,XLS,050a4447-771e-409d-9971-cc903f5f122a,https://irma.nps.gov/DataStore/DownloadFile/60...
1977588,feec6337-6fdb-455d-b274-6e86cfddb141,2,False,dataset,rocky-mountain-network-soils-database-rocky-mo...,Rocky Mountain Network Soils Database - Rocky ...,Wetlands Ecological Integrity Backend Database...,https://catalog.data.gov/dataset/rocky-mountai...,public,ACCDB,39f50e76-ff55-4d39-97c0-9579eeba0ceb,https://irma.nps.gov/DataStore/DownloadFile/60...

In [10]:
# Buscar por strings parecidas

df_similar = df[['dataset_id','nome','titulo']].drop_duplicates()

df_similar['titulo_tratado'] = df_similar['titulo'].str.replace(r'[^a-zA-Z\s]', '', regex=True).str.replace(r'\s+', ' ', regex=True).str.strip()

# Criar chave com primeiras 3 palavras
# df_similar['chave'] = df_similar['titulo'].str.lower().str.split().str[1:-2].str.join(' ')
# df_similar['chave'] = np.where(
#     df_similar['titulo_tratado'].str.split().str.len() <= 4,
#     df_similar['titulo_tratado'].str.lower(),
#     df_similar['titulo_tratado'].str.lower().str.split().str[1:-2].str.join(' ')
# )

# Contar ocorrências
contagem = df_similar['titulo_tratado'].value_counts()

# Marcar duplicatas
df_similar['tem_similar'] = df_similar['titulo_tratado'].map(contagem) > 1

# df_similar['tem_similar'] = df_similar['titulo'].apply(lambda x: tem_similar(x, df_similar))
df_similar = df_similar[df_similar['tem_similar']]

In [11]:
# Datasets com mais de um arquivo do mesmo tipo

df_qnt = df.groupby(['dataset_id','formato_arquivo'])['id_arquivo'].count().to_frame().reset_index()
df_qnt = df_qnt[df_qnt.id_arquivo > 1]

In [12]:
df = df[df.dataset_id.isin(df_qnt.dataset_id) | df.dataset_id.isin(df_similar.dataset_id)]

In [13]:
df[['dataset_id','qtd_arquivos','url','titulo']].drop_duplicates().sort_values(by=['titulo']).to_excel('./dataset_candidatos_datagov_eua.xlsx', index=False)
# df.drop_duplicates().to_excel('./dataset_candidatos_datagov_eua.xlsx', index=False)